version: "3.9"
services:
  # corex
  proteoboost:
    image: torresmateo/proteoboost:dev
    # build: 
    #   context: ./proteoboostweb
    #   dockerfile: Dockerfile.prod
    command: gunicorn proteoboostweb.wsgi:application --bind 0.0.0.0:80 -w 4
    volumes:
      #- static_proteoboost:/home/app/proteoboost/staticfiles
      - ./proteoboostweb/base/static:/home/app/proteoboost/staticfiles
      - ./proteoboostweb/base:/home/app/proteoboost/base
      - ./proteoboostweb/proteoboostweb:/home/app/proteoboost/proteoboostweb
    # uncomment these to access the app directly for test purposes, 
    # but expect everything to be broken.
    ports:
      - 8080:80
    env_file: 
      - ./.env.proteoboost.prod
    networks:
      - proteoboost
    depends_on:
      proteoboost-db:
        condition: service_healthy
  proteoboost-db:
    image: postgres:13.0-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 10 # this might seem too many retries, but there is data being copied...
    volumes:
      - proteoboost-db_data:/var/lib/postgresql/data/
      - ./proteoboost.dump.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env.proteoboost.prod.db
    networks:
      - proteoboost
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - proteoboost
  # reverse proxy
  proxy:
    build: ./reverse-proxy
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/nginx.conf
        #- static_proteoboost:/home/app/proteoboost/staticfiles
      - ./proteoboostweb/base/static:/home/app/proteoboost/staticfiles
    networks:
      - proteoboost
    ports:
      - 80:80
    depends_on:
      - proteoboost
networks:
  proteoboost:
    name: proteoboost
    external: false

volumes:
  proteoboost-db_data:
  static_proteoboost:
